"""Generate public/review/review.js from this repository's own tables.

    python3 spec/build_review_js.py

The browser has to reach the same finding as the command line, and the surest
way to fail at that is to type the synonym table twice. So the tables are read
out of testimony_convert.py and written into the JavaScript, and the matching
is ported once, below. tests_convert.py runs both over the same rows and fails
on any difference in the text they produce.

Never edit public/review/review.js by hand. Edit this, or the tables it reads,
and regenerate.

Copyright 2026 Garnet Taurus Ltd. MIT licensed.
"""
from __future__ import annotations

import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import testimony_convert as tc                              # noqa: E402

BODY = '''/* GENERATED by spec/build_review_js.py. Do not edit.
 *
 * The four questions, asked of a file of records, in the browser. The tables
 * come from spec/testimony_convert.py so the page and the command line cannot
 * reach different findings, and the suite runs both over the same rows.
 *
 * Nothing here reads the network. A file dropped on the page is read by the
 * page and never sent anywhere, which is the property that makes this usable
 * on somebody else's records at all.
 *
 * Copyright 2026 Garnet Taurus Ltd. MIT licensed.
 */
const NL = String.fromCharCode(10);
export const SYNONYMS = __SYNONYMS__;
export const QUESTIONS = __QUESTIONS__;
export const INTEGRITY_HINTS = __INTEGRITY__;
export const GENERIC = __GENERIC__;

function parts(name) {
  return name.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).sort();
}

function key(name) {
  return parts(name).join(",");
}

export function paths(row, prefix) {
  const out = {};
  if (row && typeof row === "object" && !Array.isArray(row)) {
    for (const k of Object.keys(row)) {
      const here = (prefix || "") + k;
      const v = row[k];
      if (v && typeof v === "object" && !Array.isArray(v)) {
        Object.assign(out, paths(v, here + "."));
      } else if (!Array.isArray(v)) {
        out[here] = v;
      }
    }
  }
  return out;
}

export function match(seen, member) {
  const want = SYNONYMS[member] || [member];
  const wantKeys = want.map(key);
  const memberLeaf = member.split(".").pop().toLowerCase();
  // A generic last segment names nothing on its own. `approver.id` must not
  // match `gen_ai.agent.id` because both end in `id`: that is the agent's own
  // identifier, and offering it as the approver would report the agent
  // approving itself as a person having approved.
  const bare = GENERIC.indexOf(memberLeaf) !== -1;
  let best = null, why = null;
  for (const path of Object.keys(seen)) {
    const leaf = path.split(".").pop().toLowerCase();
    if (wantKeys.indexOf(key(path)) !== -1) return [path, "the whole path matches"];
    if (!bare && (leaf === memberLeaf || want.indexOf(leaf) !== -1))
      return [path, "the name matches"];
    if (want.indexOf(leaf) !== -1) return [path, "the name matches"];
    if (parts(path).some((p) => want.indexOf(p) !== -1)) { best = path; why = "the name looks like it"; }
  }
  return best ? [best, why] : null;
}

function hasIntegrity(rows) {
  const first = rows.length ? rows[0] : {};
  for (const path of Object.keys(paths(first))) {
    const leaf = path.split(".").pop().toLowerCase();
    if (INTEGRITY_HINTS.indexOf(leaf) !== -1) return path;
    if (parts(leaf).some((p) => INTEGRITY_HINTS.indexOf(p) !== -1)) return path;
  }
  return null;
}

function pad(s, n) {
  let out = String(s);
  while (out.length < n) out += " ";
  return out;
}

export function report(rows, name) {
  const seen = {};
  for (const row of rows.slice(0, 200)) {
    const p = paths(row);
    for (const k of Object.keys(p)) if (!(k in seen)) seen[k] = p[k];
  }
  const out = [rows.length + " rows read from " + name + ".", ""];
  out.push("Of the four questions somebody asks after something goes wrong:");
  out.push("");
  let unanswerable = 0;
  for (const q of QUESTIONS) {
    const question = q[0], member = q[1], what = q[2];
    let where = null;
    if (member === "integrity") {
      where = hasIntegrity(rows);
    } else {
      const hit = match(seen, member);
      where = hit ? hit[0] : null;
    }
    if (where) {
      out.push("  " + pad("ANSWERABLE", 16) + " " + question);
      out.push("  " + pad("", 16) + " from '" + where + "'");
    } else {
      unanswerable += 1;
      out.push("  " + pad("NOT IN THE FILE", 16) + " " + question);
      out.push("  " + pad("", 16) + " nothing here looks like " + what);
    }
  }
  out.push("");
  out.push(unanswerable ? unanswerable + " of 4 are not in these rows."
                        : "All four are present in these rows.");
  __TAIL__
  return out.join(NL);
}
'''


def main() -> int:
    tail = []
    # The closing paragraphs come from the Python so the two cannot drift into
    # saying different things about the same finding.
    sample = tc.report([], "@@NAME@@").split(chr(10))
    counted = max(i for i, l in enumerate(sample)
                  if l.endswith("in these rows."))
    for line in sample[counted + 1:]:
        lit = json.dumps(line)
        # The file name is the one part that varies, so it becomes a splice
        # rather than a constant. A plain token is used because a control
        # character would be escaped by json.dumps and be harder to find again.
        lit = lit.replace("@@NAME@@", '" + name + "')
        tail.append("  out.push(%s);" % lit)

    js = (BODY
          .replace("__SYNONYMS__", json.dumps(
              {k: list(v) for k, v in tc.SYNONYMS.items()}, indent=2))
          .replace("__QUESTIONS__", json.dumps(
              [list(q) for q in tc.QUESTIONS], indent=2))
          .replace("__INTEGRITY__", json.dumps(list(tc.INTEGRITY_HINTS)))
          .replace("__GENERIC__", json.dumps(list(tc.GENERIC)))
          .replace("  __TAIL__", chr(10).join(tail)))
    out = os.path.join(HERE, "..", "public", "review", "review.js")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    io.open(out, "w", encoding="utf-8", newline="").write(js)
    print("wrote %s" % os.path.normpath(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
